/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TodoListFactoryInterface extends Interface {
  getFunction(nameOrSignature: "createTodoList"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "TodoListCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "createTodoList",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createTodoList",
    data: BytesLike
  ): Result;
}

export namespace TodoListCreatedEvent {
  export type InputTuple = [todoListAddress: AddressLike, owner: AddressLike];
  export type OutputTuple = [todoListAddress: string, owner: string];
  export interface OutputObject {
    todoListAddress: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TodoListFactory extends BaseContract {
  connect(runner?: ContractRunner | null): TodoListFactory;
  waitForDeployment(): Promise<this>;

  interface: TodoListFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createTodoList: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createTodoList"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "TodoListCreated"
  ): TypedContractEvent<
    TodoListCreatedEvent.InputTuple,
    TodoListCreatedEvent.OutputTuple,
    TodoListCreatedEvent.OutputObject
  >;

  filters: {
    "TodoListCreated(address,address)": TypedContractEvent<
      TodoListCreatedEvent.InputTuple,
      TodoListCreatedEvent.OutputTuple,
      TodoListCreatedEvent.OutputObject
    >;
    TodoListCreated: TypedContractEvent<
      TodoListCreatedEvent.InputTuple,
      TodoListCreatedEvent.OutputTuple,
      TodoListCreatedEvent.OutputObject
    >;
  };
}
